language: ruby
# Use container-based infrastructure for quicker build start-up
sudo: false

rvm:
    - 2.4.0

cache:
  bundler: true
  directories:
  - $TRAVIS_BUILD_DIR/node_modules

before_install:
    - nvm install 8

before_script: "_ci/setup.sh"
script: "_ci/build.sh"
after_success: "_ci/deploy.sh"

matrix:
  fast_finish: true

notifications:
    email: false
