# The Basics
# --------------------
title:          "9984 >> SUMMIT 2017"
description:    "Blockchain Futures for Developers, Enterprises & Society"
url:            "https://2017.9984.io"
email:          "hello@9984.io"

github:
    org:        "9984"
    repo:       "2017.9984.io"

analyticsID:    "UA-60614729-10"

# Collections
# --------------------
collections:
    speakers:
        output: true

defaults:
    - scope:
        path: ""
        type: speakers
      values:
        layout: speaker


# Urls
# --------------------
permalink:      /:title/


# Content Parsing
# --------------------
markdown:       redcarpet

redcarpet:
    extensions: ['no_intra_emphasis', 'autolink', 'tables', 'smart', 'hard_wrap', 'fenced_code_blocks', 'strikethrough', 'highlight', 'quote', 'footnotes', 'with_toc_data', 'space_after_headers', 'superscript', 'lax_spacing']


# Generator
# --------------------
source:         ./_src
destination:    ./_dist


# Plugins
# --------------------
plugins:
    - jekyll-sitemap
    - jekyll-redirect-from

exclude:
    - "*README.md"
